"""Regression tests for the ``wake_losses`` CLI runner on the La Haute Borne example data.

The expected values were generated by running ``examples/configs/wake_losses.yaml`` through
``python -m openoa.cli run wake_losses`` (``seed: 42``) twice and confirming identical output. The
non-UQ values match the notebook ``examples/06_wake_loss_analysis.ipynb`` and
``test/regression/wake_losses.py``; the UQ values use ``num_sim: 5`` to keep the runtime short.
"""

from __future__ import annotations

import json
from copy import deepcopy
from pathlib import Path

import numpy as np
import pytest
import numpy.testing as npt

from openoa.cli import main, get_runner
from openoa.runners import load_config

REPO_ROOT = Path(__file__).resolve().parents[2]
CONFIG_PATH = REPO_ROOT / "examples" / "configs" / "wake_losses.yaml"

TURBINE_IDS = ["R80711", "R80721", "R80736", "R80790"]

# Fractional wake losses (multiply by 100 for percentages), asserted to 6 decimal places.
EXPECTED_POR = 0.00340045
EXPECTED_LT = 0.00373332
EXPECTED_TURBINE_POR = [-0.11727658, 0.10898059, 0.04065239, -0.01910556]
EXPECTED_TURBINE_LT = [-0.09713340, 0.10282598, 0.02933038, -0.02034775]

UQ_RUN_OVERRIDES = {
    "UQ": True,
    "num_sim": 5,
    "run": {"no_wakes_ws_thresh_LT_corr": 15.0, "reanalysis_products": ["merra2", "era5"]},
}
EXPECTED_UQ_POR = [0.02261792, -0.00803726, 0.02286098, -0.01784245, 0.02030258]
EXPECTED_UQ_LT = [0.02612285, -0.00438320, 0.01971720, -0.01231300, 0.02226108]
EXPECTED_UQ_POR_MEAN = 0.00798035
EXPECTED_UQ_POR_STD = 0.01738338
EXPECTED_UQ_LT_MEAN = 0.01028099
EXPECTED_UQ_LT_STD = 0.01555028
EXPECTED_UQ_TURBINE_POR_MEAN = [-0.11106930, 0.11272210, 0.04484654, -0.01486588]
EXPECTED_UQ_TURBINE_LT_MEAN = [-0.09083556, 0.11080693, 0.03528052, -0.01435420]
EXPECTED_UQ_TURBINE_POR_STD = [0.01948831, 0.01559998, 0.01717654, 0.01731770]
EXPECTED_UQ_TURBINE_LT_STD = [0.01975747, 0.01204952, 0.01370444, 0.01720099]

DECIMAL = 6


@pytest.fixture(scope="module")
def base_config() -> dict:
    return load_config(CONFIG_PATH)


def _assert_non_uq_results(results: dict) -> None:
    assert results["analysis_type"] == "WakeLosses-scada"
    assert results["UQ"] is False
    assert results["turbine_ids"] == TURBINE_IDS
    npt.assert_almost_equal(results["wake_losses_por"], EXPECTED_POR, decimal=DECIMAL)
    npt.assert_almost_equal(results["wake_losses_lt"], EXPECTED_LT, decimal=DECIMAL)
    npt.assert_almost_equal(
        results["turbine_wake_losses_por"], EXPECTED_TURBINE_POR, decimal=DECIMAL
    )
    npt.assert_almost_equal(results["turbine_wake_losses_lt"], EXPECTED_TURBINE_LT, decimal=DECIMAL)
    assert np.shape(results["wake_losses_por_wd"]) == (72,)
    assert np.shape(results["turbine_wake_losses_lt_wd"]) == (4, 72)


def test_cli_wake_losses_runner(base_config: dict, tmp_path: Path) -> None:
    results = get_runner("wake_losses").run(deepcopy(base_config), tmp_path)
    _assert_non_uq_results(results)

    written = json.loads((tmp_path / "wake_losses_results.json").read_text())
    _assert_non_uq_results(written)


def test_cli_wake_losses_main_entry_point(tmp_path: Path, capsys: pytest.CaptureFixture) -> None:
    exit_code = main(
        ["run", "wake_losses", "--config", str(CONFIG_PATH), "--output-dir", str(tmp_path)]
    )
    assert exit_code == 0
    written = json.loads((tmp_path / "wake_losses_results.json").read_text())
    _assert_non_uq_results(written)
    assert "wake_losses_por" in capsys.readouterr().out


def test_cli_wake_losses_runner_uq(base_config: dict, tmp_path: Path) -> None:
    config = deepcopy(base_config)
    config["analysis"].update(deepcopy(UQ_RUN_OVERRIDES))

    results = get_runner("wake_losses").run(config, tmp_path)

    assert results["UQ"] is True
    assert results["num_sim"] == 5
    npt.assert_almost_equal(np.ravel(results["wake_losses_por"]), EXPECTED_UQ_POR, decimal=DECIMAL)
    npt.assert_almost_equal(np.ravel(results["wake_losses_lt"]), EXPECTED_UQ_LT, decimal=DECIMAL)
    npt.assert_almost_equal(results["wake_losses_por_mean"], EXPECTED_UQ_POR_MEAN, decimal=DECIMAL)
    npt.assert_almost_equal(results["wake_losses_por_std"], EXPECTED_UQ_POR_STD, decimal=DECIMAL)
    npt.assert_almost_equal(results["wake_losses_lt_mean"], EXPECTED_UQ_LT_MEAN, decimal=DECIMAL)
    npt.assert_almost_equal(results["wake_losses_lt_std"], EXPECTED_UQ_LT_STD, decimal=DECIMAL)
    npt.assert_almost_equal(
        results["turbine_wake_losses_por_mean"], EXPECTED_UQ_TURBINE_POR_MEAN, decimal=DECIMAL
    )
    npt.assert_almost_equal(
        results["turbine_wake_losses_lt_mean"], EXPECTED_UQ_TURBINE_LT_MEAN, decimal=DECIMAL
    )
    npt.assert_almost_equal(
        results["turbine_wake_losses_por_std"], EXPECTED_UQ_TURBINE_POR_STD, decimal=DECIMAL
    )
    npt.assert_almost_equal(
        results["turbine_wake_losses_lt_std"], EXPECTED_UQ_TURBINE_LT_STD, decimal=DECIMAL
    )
